# Generated by Django 6.0.2 on 2026-02-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
